### ISSUE TITLE
Simulation time recorded as NaN in upgrade summary files

### ISSUE THREAD

**Issue by daniel-thom** [NREL/disco#118]
The upgrades module records `np.NaN` as the initialization value for simulation time. This shows up in the Initial Stage, which seems a bit odd. Would `0.0` or `null`/`None` be more appropriate? Does it even belong here since it doesn't really apply to the Initial Stage?

**Comment by ann-sherin** [comment]
Yes, it doesnt apply to the "Initial" stage, but because initial and final have the same fields, I put it in there. 
We could initialize it to 0, if that's fine.
