### ISSUE TITLE
Transformer file output formatting

### ISSUE THREAD

**Issue by daniel-thom** [NREL/disco#126]
The transformer_upgrades.json file 

1. Defines the `conn` field like this:
```
"conn": "wye ",
```
Does the value need to have the trailing space removed?

2. Does this value need to be changed to an array of floats?
```
"Xscarray": "[2.4, 1.6, 2.4]",
```

3. Is this the correct type?
```
"taps": "['1', '1', '1']",
```

If this file is just a dump of an opendssdirect dataframe and no one is ever supposed to look at it, maybe none of this matters.

**Comment by ann-sherin** [comment]
Changed to be of sensible datatypes
