### ISSUE TITLE
What upgrade outputs get delivered to URBANopt?

### ISSUE THREAD

**Issue by daniel-thom** [NREL/disco#127]
The current plan is to deliver `upgrade_summary.json` back to URBANopt. It has summary information of violations and costs.

We are also planning to report locations of DISCO-generated .dss files that define the upgraded network, which will allow users to load the new network in OpenDSS.

The following files have information that is potentially interesting to end users. Do we want to do anything with these other than leave them in the output directory?
- feeder_stats.json
- VoltageUpgrades/voltage_upgrades.json
- ThermalUpgrades/transformer_upgrades.json
- ThermalUpgrades/line_upgrades.json
- UpgradeCosts/thermal_upgrade_costs.json
- UpgradeCosts/voltage_upgrade_costs.json

**Comment by ann-sherin** [comment]
TBD: 
Have a json file that is succinct, draft header names:
equipment_type, equipment_name, status, original_parameter, new_parameter

Status can have values: untouched, replaced, new, setting_changed .....
