### ISSUE TITLE
Installation for "Developer" access

### ISSUE THREAD

**Issue by temcdrm** [NREL/disco#173]
This works: `git clone https://github.com/NREL/disco.git`

This, from read the docs, may be for the internal repository? `git clone git@github.com:NREL/disco.git`

**Comment by daniel-thom** [comment]
`git@github.com` is for the git+ssh protocol. I'll update it to use http, which should be better since the repo is public. Thanks.

**Comment by daniel-thom** [comment]
The docs are now updated.
