### ISSUE TITLE
DISCO hosting capacity reports database schema

### ISSUE THREAD

**Issue by jgu2** [NREL/disco#43]
It's worth to store the hosting capacity reports of DISCO into a database, as it facilitates the metrics query and result comparison dynamically among feeders.

The database schema is shown below,
![disco-db](https://user-images.githubusercontent.com/50031970/140774646-5c1ef983-52e0-4b77-8fba-5813c7c00e24.png)

Feel free to comment if any question or suggestions!

**Comment by daniel-thom** [comment]
@jgu2 Can we close this?

**Comment by jgu2** [comment]
Yes, the db schema already implemented and is now in use, it could be closed.

**Comment by jgu2** [comment]
> @jgu2 Can we close this?

Yes, the db schema already implemented and is now in use, it could be closed.
